In [1]:
import pandas as pd
import numpy as np

In [2]:
#import the original security wait times data for all U.S. airports
waittimes_df = pd.read_excel("security_wait_times.xls")
waittimes_df

,Code,Airport,Checkpoint,2015 December,2014 December,2013 December,2012 December,2011 December,2010 December,2009 December,...,2015 January,2014 January,2013 January,2012 January,2011 January,2010 January,2009 January,2008 January,2007 January,2006 January
0,ABE,Lehigh Valley International,ABE Main Terminal,2.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0
1,ABI,Abilene Regional Airport,ABIA,NaN,1.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,NaN
2,ABQ,Albuquerque International Sunport,Checkpoint for A/B Gates,10.0,NaN,NaN,NaN,NaN,1.0,2.0,...,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN
3,ABY,Southwest Georgia Regional,ABY-A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN
4,ACK,Nantucket Memorial,Main Terminal - 1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
754,WYS,West Yellowstone,WYSZ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
755,XNA,Northwest Arkansas Regional,Checkpoint 2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
756,YAK,Yakutat,YAK-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
757,YKM,Yakima Air Terminal,YKM Main,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
758,YNG,Youngstown-Warren Regional,Gate,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN

In [3]:
#deal with merged cells of one airport corresponding to multiple checkpoints from the original excel file
waittimes_df['Code'] = pd.Series(waittimes_df['Code']).fillna(method='ffill')
waittimes_df['Airport'] = pd.Series(waittimes_df['Airport']).fillna(method='ffill')

In [4]:
#calculate average security wait times of each airport based on data available
#store the values in a new column
avg_wait_time = waittimes_df.groupby("Code")[waittimes_df.columns[3:]].apply(np.nanmean)
waittimes_df['avg_wait_time'] = avg_wait_time[waittimes_df.Code].values

In [5]:
#remname column names so that they fit Python naming conventions
waittimes_df = waittimes_df.rename(columns={'Code':'airport_code', 'Airport':'airport_name'})

In [6]:
#drop unncessary columns and rows and set airport code as index
waittimes_df = waittimes_df.drop(columns=waittimes_df.columns[2:-1])
waittimes_df = waittimes_df.drop_duplicates()
waittimes_df = waittimes_df.set_index('airport_code')
waittimes_df

                                   airport_name  avg_wait_time
airport_code
ABE                 Lehigh Valley International       2.450000
ABI                    Abilene Regional Airport       1.416667
ABQ           Albuquerque International Sunport       2.974359
ABY                  Southwest Georgia Regional       1.583333
ACK                          Nantucket Memorial       1.500000
...                                         ...            ...
WYS                            West Yellowstone       3.428571
XNA                 Northwest Arkansas Regional       1.555556
YAK                                     Yakutat       3.444444
YKM                         Yakima Air Terminal       1.666667
YNG                  Youngstown-Warren Regional       1.000000

[386 rows x 2 columns]